### PR TITLE
Add ability to parse procspec in getspec

### LINKED ISSUE #51: allow pavo to read OOI files
I did some research and found out OceanOptic's OOI Binary files are just zipped files with a couple of metadata files and one XML file that has the main spectra info. We could use `unzip()` and `tempfile()` to open the file in R and save its contents in a temporary folder, then extract the reflectance data from the XML file. I tried giving it a go but am having problems with interpreting the encoding. I can't follow through on this right now but could be a good project if anyone wants a test case to learn how to program machine-reading in R...

### PR DESCRIPTION
**Pull request by Bisaloo**
Some comments:

- After giving it some thought, I believe the best and cleanest option is to add a separate function to parse individual procspec files. This is the job of the internal function `parse_procspec()`. I didn't list it in the `NAMESPACE` so it shouldn't be visible to users (unless they dig around, that's why I added a minimal documentation nonetheless)
- Apologies for the mess with whitespaces. Trailing whitespaces are automatically removed by my text editor. You can add `?w=1` at the end of the github diff url to hide those changes. [Link to diff without whitespaces](https://github.com/rmaia/pavo/pull/71/files?w=1)
- I am not familiar with R packages development. I tried to follow instructions from Hadley's book but please let me know if something is wrong

fix #51

### CODE REVIEW

**Comment by Bisaloo** [comment]
@rmaia, I see you have been solving conflicts. Feel free to let me know if you need me to rebase my pull request on top on current master.

**Comment by rmaia** [comment]
It's cool, it's a small conflict I created myself by changing `getspec` after you sent your pull request. I'm making some minor changes to the code and will merge in a sec!

**Comment by rmaia** [comment]
ugh I messed up and made another branch. I'll merge this & then that one next

**Comment by Bisaloo** [comment]
Great, thank you! I am watching this repo but don't hesitate to ping me if an issue related to this comes up on here or on the gitter.

**Comment by rmaia** [comment]
cool, I made a mess but I think it's sorted out now, haha. Main thing was changing packages to suggests instead of imports, so they don't need to be installed and loaded every time, even if the user isn't importing any ProcSpec files. Main relevant commits:

https://github.com/rmaia/pavo/commit/0de1e37a9b69a9ae6a39d7ce905260da410de397
https://github.com/rmaia/pavo/commit/102719d9e7c0a75cbc0c4a80248dc5e778e1c479

Thanks for doing this!

**Pull request merged**
