### PR TITLE
Add option to plot cone names to tetraplot

### PR DESCRIPTION
**Pull request by Bisaloo**
```r
data(sicalis)
vis_sicalis = vismodel(sicalis)
tcs_sicalis = colspace(vis_sicalis)
tetraplot(tcs_sicalis, conenames = TRUE)
```
rplot05

This code is kind of a hack and I'm not particularly happy with it but I think this option would be nice. 

It's also good for parity with other plots such as `triplot`. Btw, it makes me realize it might make more sense to name this new arg `label` to be coherent with other functions. What do you think?

### CODE REVIEW

**Comment by Bisaloo** [comment]
I forgot to add a default value. Should it be on or off?

**Comment by Bisaloo** [comment]
> Doe it work okay with the variable 3D orientations?

That's why I'm not super happy with it. It does not anything clever to ensure this does always work. But from what I can tell, it still works okay in most cases. One thing I could do is increase the margins so it doesn't get clipped.

rplot_-30_200
rplot_345_249
rplot_345_49
rplot_345_125
rplot_45_125
rplot_145_25
rplot_90_90
rplot_0_90

**Comment by Bisaloo** [comment]
Oh wait, I may have a better idea.

**Comment by Bisaloo** [comment]
What do you think of the examples below with a new method?

<details><summary>Pictures</summary>

rplot_-30_200
rplot_345_125
rplot_345_249
rplot_345_49
rplot_145_25
rplot_45_125
rplot_0_90
rplot_90_90

</details>

**Comment by Bisaloo** [comment]
I also added some misc doc fixes (`vol` and `tcsplot`).

**Comment by thomased** [comment]
Cool! Looks tidy. Nice to give users the option.

**Pull request merged**
