### PR TITLE
Simplify and speed up vismodel

### PR DESCRIPTION
**Pull request by Bisaloo**
WIP because I still need to run some tests to make sure everything works as expected. Plus, I'll add some benchmarks (should be faster)

### CODE REVIEW

**Comment by Bisaloo** [comment]
```r
library(microbenchmark)

my_check <- function(values) {
  all.equal(values[[1]], values[[2]])
}

data(sicalis)

microbenchmark({vismodel(sicalis)},
               {pavo::vismodel(sicalis)},
               check = my_check)
```

> |expr                            |      min|       lq|     mean|   median|       uq|      max| neval|cld |
> |:-------------------------------|--------:|--------:|--------:|--------:|--------:|--------:|-----:|:---|
> |{     vismodel(sicalis) }       | 11.45658| 11.65306| 12.17624| 11.80448| 12.11572| 23.77368|   100|a   |
> |{     pavo::vismodel(sicalis) } | 31.34660| 31.59700| 32.88465| 31.96391| 32.88034| 39.05751|   100|b   |
  
```r
microbenchmark({vismodel(sicalis, visual = "cie10")},
               {pavo::vismodel(sicalis, visual = "cie10")},
               check = my_check)
```

> |expr                                              |      min|       lq|     mean|   median|       uq|      max| neval|cld |
> |:-------------------------------------------------|--------:|--------:|--------:|--------:|--------:|--------:|-----:|:---|
> |{     vismodel(sicalis, visual = "cie10") }       | 10.16220| 10.29052| 10.70352| 10.35369| 10.44599| 16.15071|   100|a   |
> |{     pavo::vismodel(sicalis, visual = "cie10") } | 24.69053| 24.89448| 25.93845| 25.02794| 25.40837| 35.95674|   100|b   |

It looks fine. Maybe we should wait until the tests are fixed and I will rebase this PR to make sure it doesn't break anything.

**Comment by thomased** [comment]
Looks cool. I suspect the sha1 tests might just need to be reset due to tiny floating-point differences — not sure if there's much to be done there.

**Comment by Bisaloo** [comment]
I'll try to have a look to see if that's an OS thing or just an issue with travis.

**Comment by thomased** [comment]
I don't know if the minor convenience of `isFALSE` is worth forcing the use of `R(>=3.1)` on users? (We're currently okay right back to `R(>= 2.10)`). People generally aren't on the latest version — I think it might just be another point of friction.

**Comment by Bisaloo** [comment]
Yes, I agree. I didn't think about this at the beginning. I'll change it back tomorrow.

**Comment by Bisaloo** [comment]
New tests: 

``` r
library(microbenchmark)

source("../R/vismodel.R")
library(pavo)
```

    ## 
    ## Attaching package: 'pavo'

    ## The following object is masked _by_ '.GlobalEnv':
    ## 
    ##     vismodel

``` r
vissyst = pavo:::vissyst
transmissiondata = pavo:::transmissiondata
bgandilum = pavo:::bgandilum

my_check <- function(values) {
  all.equal(values[[1]], values[[2]])
}

data(sicalis)

test1 <- microbenchmark({vismodel(sicalis)},
                        {pavo::vismodel(sicalis)},
                        check = my_check)
knitr::kable(summary(test1))
```

| expr                        |       min |        lq |      mean |    median |        uq |      max | neval | cld |
| :-------------------------- | --------: | --------: | --------: | --------: | --------: | -------: | ----: | :-- |
| { vismodel(sicalis) }       |  7.905351 |  8.060483 |  8.430466 |  8.182187 |  8.333426 | 15.68619 |   100 | a   |
| { pavo::vismodel(sicalis) } | 30.832503 | 31.108574 | 32.368753 | 31.921038 | 33.952092 | 35.47040 |   100 | b   |

``` r
test2 <- microbenchmark({suppressWarnings(vismodel(sicalis, visual = "cie10"))},
                        {suppressWarnings(pavo::vismodel(sicalis, visual = "cie10"))},
                        check = my_check)
knitr::kable(summary(test2))
```

| expr                                                            |       min |       lq |      mean |    median |        uq |      max | neval | cld |
| :-------------------------------------------------------------- | --------: | -------: | --------: | --------: | --------: | -------: | ----: | :-- |
| { suppressWarnings(vismodel(sicalis, visual = “cie10”)) }       |  8.996394 |  9.14985 |  9.553266 |  9.261879 |  9.503141 | 14.30365 |   100 | a   |
| { suppressWarnings(pavo::vismodel(sicalis, visual = “cie10”)) } | 24.700975 | 24.98875 | 25.829681 | 25.216352 | 26.033167 | 30.33518 |   100 | b   |

``` r
test3 <- microbenchmark({vismodel(sicalis, relative = TRUE)},
                        {pavo::vismodel(sicalis, relative = TRUE)},
                        check = my_check)
knitr::kable(summary(test3))
```

| expr                                         |       min |        lq |      mean |    median |        uq |      max | neval | cld |
| :------------------------------------------- | --------: | --------: | --------: | --------: | --------: | -------: | ----: | :-- |
| { vismodel(sicalis, relative = TRUE) }       |  7.921777 |  8.075527 |  8.292881 |  8.161449 |  8.329809 | 12.68186 |   100 | a   |
| { pavo::vismodel(sicalis, relative = TRUE) } | 30.893564 | 31.132380 | 32.500476 | 31.714350 | 32.706171 | 38.79124 |   100 | b   |

``` r
test4 <- microbenchmark({vismodel(sicalis, visual = pavo:::vissyst[,c("wl", grep("^canis", colnames(pavo:::vissyst), value = TRUE))])},
                        {pavo::vismodel(sicalis, visual = pavo:::vissyst[,c("wl", grep("^canis", colnames(pavo:::vissyst), value = TRUE))])},
                        check = my_check)
knitr::kable(summary(test4))
```

| expr                                                                                                                      |       min |       lq |      mean |    median |        uq |       max | neval | cld |
| :------------------------------------------------------------------------------------------------------------------------ | --------: | -------: | --------: | --------: | --------: | --------: | ----: | :-- |
| { vismodel(sicalis, visual = pavo:::vissyst\[, c(“wl”, grep(“^canis”, colnames(pavo:::vissyst), value = TRUE))\]) }       |  7.552277 |  7.70836 |  9.596712 |  7.814108 |  8.018862 | 160.60426 |   100 | a   |
| { pavo::vismodel(sicalis, visual = pavo:::vissyst\[, c(“wl”, grep(“^canis”, colnames(pavo:::vissyst), value = TRUE))\]) } | 19.797007 | 19.93009 | 20.603891 | 20.160306 | 20.615696 |  26.06826 |   100 | b   |

**Pull request merged**
