### PR TITLE
Fix bin width computation for procspec bin option

### PR DESCRIPTION
**Pull request by Bisaloo**
procspec currently fails for some bins values. This PR fixes this. I think this is the best way to handle things but I am open to suggestions as well.

``` r
library(pavo)
data(sicalis)
procspec(sicalis, opt = "bin", bins = 24)
#> Warning in matrix(unlist(rspecdata), nrow = bins, byrow = T): data length
#> [525] is not a sub-multiple or multiple of the number of rows [24]
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 25, 24
procspec(sicalis, opt = "bin", bins = 33)
#> processing options applied:
#>  binned spectra to 12-nm intervals
#> 
#>     wl     ind1.C     ind1.T     ind1.B     ind2.C    ind2.T     ind2.B
#> 1  300  1.1419746  4.1624476  2.8594889 0.60686270  3.802984  2.3266032
#> 2  312  2.1732762  7.1474000  5.3918381 1.80273571  6.006286  4.4642857
#> 3  324  2.8145937  9.0554952  7.3668222 2.14179921  7.913873  6.5839841
#> 4  336  3.1835460  9.5906381  8.3863460 2.22855000  9.329016  7.4952698
#> 5  348  2.8872667  9.6216857  8.4711556 2.08110000  9.803095  7.9326984
#> 6  360  2.6401016  8.2763683  7.4543619 1.98722778  9.847571  7.4123016
#> 7  372  1.6003873  5.9392254  5.4160127 1.24351349  9.150016  5.6684444
#> 8  384  1.1564667  4.1812667  3.6034000 0.77100556  8.200000  4.0036000
#> 9  396  0.6452762  2.5299714  2.0677587 0.40764048  7.099349  2.5887460
#> 10 408  0.4021000  1.7328333  1.1415833 0.20986667  6.260917  1.5958833
#> 11 420  0.2632333  1.0901778  0.4803778 0.08786270  5.414250  0.8798889
#> 12 432  0.2847000  0.9689333  0.4888000 0.06881667  5.463967  0.8216667
#> 13 444  0.2033000  0.7344667  0.1651333 0.04378333  4.906867  0.4928333
#> 14 456  0.3809667  1.0356333  0.5075833 0.16158333  5.381383  0.7496000
#> 15 468  0.4623000  1.4212667  0.9836500 0.28918333  6.160800  1.3120667
#> 16 480  0.3536167  1.0715500  0.4843000 0.23020000  5.631267  0.9273000
#> 17 492  1.2388000  3.2687333  2.9434667 0.99911667  8.337867  3.3860000
#> 18 504  3.9417333  9.7809000 10.6301000 3.13275000 13.290267  9.9164667
#> 19 516  6.4543263 14.6908386 16.0197754 4.84909912 15.618088 13.9920175
#> 20 528  7.4950000 16.1054000 17.8177333 5.49038333 16.299933 15.2438000
#> 21 540  8.3127333 16.9644000 19.1379333 5.97831667 16.747333 16.1008000
#> 22 552  9.0330333 17.5009167 20.0730833 6.40628333 17.037033 16.7910000
#> 23 564  9.3034140 17.6879965 20.4596702 6.46380088 17.179211 17.0566140
#> 24 576  9.6328833 17.8547167 20.8087053 6.78236667 17.280933 17.3523667
#> 25 588  9.8045500 17.9739614 21.1412842 6.90368333 17.313050 17.5595439
#> 26 600  9.9742737 17.9350140 21.3654246 7.08466053 17.452246 17.6791754
#> 27 612 10.4018175 18.0401368 21.7008632 7.37261667 17.503193 18.0039123
#> 28 624 10.6255544 18.0861667 21.8084667 7.33829211 17.476263 18.0076842
#> 29 636 10.6360982 18.1451719 22.0185474 7.43709912 17.541579 18.1949815
#> 30 648 11.0164842 18.2907684 22.1333018 7.62595877 17.543368 18.2365614
#> 31 660 11.2022386 18.1175930 22.3217228 7.89997632 17.306035 18.6015088
#> 32 672 11.3039852 18.1939614 22.2337754 7.54374630 17.591000 18.6094444
#> 33 684 11.3596421 18.1928737 22.3508037 7.60419074 17.334111 18.7178421
#>       ind3.C     ind3.T    ind3.B     ind4.C     ind4.T      ind4.B
#> 1  0.3181746  2.5759206  2.691794  0.5990000  1.6117016  1.28934921
#> 2  0.7946349  4.3117302  4.411333  1.0910000  3.0908762  2.80328571
#> 3  0.8498413  5.7516349  6.087587  1.3967143  4.4971143  4.15815873
#> 4  1.1353968  6.3180000  7.103524  1.5125079  5.4687492  5.16096825
#> 5  0.8885397  6.5170111  7.137730  1.6529524  5.7327333  5.38557143
#> 6  0.7922540  6.1196825  6.875413  1.4678889  4.7804159  4.66914286
#> 7  0.4835873  4.8492063  5.549206  0.9371111  3.5456857  3.27268254
#> 8  0.2970476  3.5952444  4.263733  0.5881270  2.3088667  1.99666667
#> 9  0.2173968  2.4054286  2.797683  0.3649833  1.3107968  0.97823810
#> 10 0.1783563  1.6603278  2.005767  0.2919333  0.8456500  0.57318333
#> 11 0.1603175  1.1398889  1.264917  0.2818000  0.4347333  0.23691667
#> 12 0.2121230  1.1311778  1.280133  0.2742500  0.3923333  0.24381667
#> 13 0.1469841  0.7432111  0.912000  0.2877778  0.1425667  0.02943333
#> 14 0.2325397  1.1364111  1.283000  0.3509667  0.4119000  0.23690000
#> 15 0.2275397  1.5742444  1.857000  0.4418333  0.7462667  0.54065000
#> 16 0.2109063  1.2115444  1.364200  0.3027833  0.4065667  0.28468333
#> 17 0.4794730  3.3260444  3.928067  0.6093333  1.9278000  1.86853333
#> 18 2.1143730  8.4645111  9.730200  2.8552000  7.2745667  7.39860000
#> 19 4.0408906 11.3882690 12.596281  6.0251754 11.3000316 11.85382456
#> 20 4.8281397 12.2932444 13.404267  7.3713333 12.6397333 13.46993333
#> 21 5.4276063 12.9278444 14.016867  8.4238000 13.4931333 14.62906667
#> 22 5.7840730 13.2223278 14.493183  9.1373833 14.0911833 15.50453333
#> 23 6.1157151 13.4741111 14.588596  9.5008246 14.2798386 15.72047368
#> 24 6.2338028 13.5476278 14.753737  9.7434912 14.5406333 16.16357895
#> 25 6.3409432 13.6646725 14.911200  9.9376842 14.6234000 16.28457895
#> 26 6.4907397 13.7619444 15.112474 10.2444561 14.6551368 16.55547368
#> 27 6.5687678 13.9726111 15.192351 10.4757544 14.7806667 16.77196491
#> 28 6.6279081 14.1326550 15.313281 10.5554737 14.8916632 16.89471930
#> 29 6.7765572 14.3600370 15.473404 10.4524912 14.9851018 17.06291228
#> 30 6.9030134 14.2467427 15.462105 10.6080702 14.9850316 17.17587719
#> 31 7.0343818 14.4023567 15.656333 10.7432807 14.9616632 17.03454386
#> 32 6.9262941 14.4017778 15.634333 10.7105263 14.8366105 17.16866667
#> 33 6.6619841 14.1875322 15.352246 10.7038421 14.7488737 17.28281481
#>        ind5.C    ind5.T    ind5.B    ind6.C    ind6.T    ind6.B     ind7.C
#> 1   0.6879317  3.370746  3.337265 0.1835873  3.458095  4.454397  0.3900254
#> 2   1.1055032  5.863524  6.046043 0.5011905  6.084968  6.210333  0.8535333
#> 3   1.9514556  8.155714  7.385424 0.4674921  8.052032  7.429381  1.6334222
#> 4   2.1684889  9.372349  8.422067 1.0652698  9.431270  8.359600  2.1379460
#> 5   2.0728841  9.663033  8.392138 1.3814603 10.089000  8.769883  2.1889310
#> 6   1.7188206  8.969048  7.665995 1.3926667  9.723365  8.117921  1.6979143
#> 7   0.7672016  7.049127  5.937075 1.0593016  8.514365  7.134460  0.8444063
#> 8   0.4712492  5.636333  4.450567 0.8254603  7.359416  5.981467  0.6712976
#> 9   0.2355190  3.741460  2.971694 0.7300825  5.702190  4.923524  0.4927238
#> 10  0.1802651  3.009950  2.129050 0.5754492  4.878299  4.097167  0.3187476
#> 11  0.1842175  2.148833  1.423067 0.5771492  4.014127  3.439111  0.3119143
#> 12  0.2036389  2.158867  1.431567 0.6109825  3.952149  3.315500  0.3077810
#> 13  0.1884556  1.727267  1.078717 0.5961492  3.411916  2.925778  0.2932476
#> 14  0.2509222  2.142483  1.491733 0.7115325  3.853533  3.280783  0.3823976
#> 15  0.2981222  2.734867  1.951700 0.7562825  4.538949  3.957733  0.3849810
#> 16  0.2670889  2.257233  1.469833 0.7872825  4.116683  3.479800  0.4091143
#> 17  0.6255889  4.963600  3.864967 1.3140159  6.732349  5.650667  0.7929143
#> 18  2.9305889 11.570700  9.823033 3.4319492 12.799883 10.137100  3.2896810
#> 19  6.4335433 15.164211 13.291233 5.2665422 16.046928 12.233211  7.0755108
#> 20  7.8927889 16.144000 14.373433 6.0556159 16.982749 12.791667  8.7097143
#> 21  8.8973222 16.698667 15.156300 6.5366825 17.481283 13.195533  9.9407810
#> 22  9.4577222 16.953917 15.628717 6.8596659 17.638649 13.483596 10.7672976
#> 23  9.8173327 17.091246 15.810128 7.0920825 17.787402 13.585933 11.1903178
#> 24 10.0105959 17.189088 16.132417 7.1903317 17.905911 13.674579 11.5631976
#> 25 10.1855222 17.336133 16.294777 7.3789992 17.890121 13.752684 11.5814476
#> 26 10.2927363 17.364649 16.480777 7.5441738 17.894297 13.845825 12.0580722
#> 27 10.4692889 17.283123 16.620988 7.7022966 17.958753 14.032018 12.1394406
#> 28 10.4546485 17.415947 16.698953 7.6757352 17.995261 14.139316 12.2368792
#> 29 10.7584556 17.217123 17.005830 7.8001085 17.856630 14.222316 12.4058090
#> 30 10.6371924 17.174649 17.098882 7.7750159 17.785928 14.065789 12.4561774
#> 31 10.6597713 17.153684 17.017584 7.6459106 17.743460 14.053737 12.5204932
#> 32 10.6353152 17.342246 17.009181 7.7245071 17.571174 13.879351 12.5438617
#> 33 10.6307713 16.871912 17.057304 7.6736825 17.501595 13.812070 12.6412476
#>        ind7.T     ind7.B
#> 1   2.1046190  1.6094921
#> 2   4.2104762  3.7968571
#> 3   5.9159524  5.8714603
#> 4   6.7483333  6.8366190
#> 5   7.0473333  7.5954500
#> 6   6.1233810  7.5206667
#> 7   4.4451270  5.8403968
#> 8   3.0440667  4.3937333
#> 9   1.7717460  2.7298095
#> 10  1.1273667  1.8617333
#> 11  0.6433333  1.1636667
#> 12  0.6203333  1.1104667
#> 13  0.4101333  0.7487833
#> 14  0.6316167  1.1614000
#> 15  1.0159833  1.6831667
#> 16  0.6783833  1.3396667
#> 17  2.6092000  4.1826667
#> 18  8.7268667 12.0347667
#> 19 12.6968070 17.0612807
#> 20 13.9910000 18.7637333
#> 21 14.8413333 19.6667333
#> 22 15.3987333 20.1471000
#> 23 15.6284912 20.5115965
#> 24 15.8543333 20.6802807
#> 25 15.9053667 20.8560351
#> 26 16.1178421 20.9897719
#> 27 16.2370526 21.1064333
#> 28 16.4018947 21.1568246
#> 29 16.5411404 21.1368333
#> 30 16.5360702 21.1980000
#> 31 16.6154912 21.2576667
#> 32 16.6456296 21.0465789
#> 33 16.5549825 21.1298148
```

### CODE REVIEW

**Comment by Bisaloo** [comment]
Another option would be to simply change `seq(min(wl), by=bw, lengh.out = bins)` in the first commit but not the rest. I'm not entirely sure what would be best.

**Comment by Bisaloo** [comment]
Actually, I think I found a better solution, please don't merge this yet.

**Comment by Bisaloo** [comment]
nevermind, it's actually good to review

**Comment by thomased** [comment]
I think Travis is just having a bad day here, as it all looks good & clear to me locally. Let's see...

**Pull request merged**
