### PR TITLE
Add option to plot light spectrum in plot.rspec

### PR DESCRIPTION
**Pull request by Bisaloo**
Almost everybody added this kind of spectrum to the xaxis in their spectra at ESEB2019. I think it shows a strong need for this. It's better if that's included in pavo because:
- it doesn't require manual editing with image editing software.
- we can make sure it's correct: I've seen many spectra with large variations of brightness and some made it overlap with UV range.

Rplot05

TODO:
- [x] Tweak vertical position
- [x] Adjust height depending on ylim(?)
- [x] Find a better name for this new arg
- [x] Make it work with `type = "heatmap"` (or if we'd rather not, then print a warning)
- [x] Update changelog
- [ ] Mention it in the vignette

### CODE REVIEW

**Comment by Bisaloo** [comment]
Would something like this figure from [Rashid et al. (2018)](10.1002/adom.201701218) be useful as well?

Screenshot from 2019-10-30 14-01-32

It's nice on the eyes but I am not sure it conveys an accurate idea of what spectral reflectance is.

**Comment by thomased** [comment]
Neat idea. Could be a bit of fun for presentations etc. I think I'd favour the simpler one (underneath-bar) over that as a ready option if anyone finds time to put into it, but it's worth a thought.

**Comment by Bisaloo** [comment]
Once we find a better name for the new arg, I think this is ready for review and can be merged into master.

Regarding https://github.com/rmaia/pavo/pull/168#issuecomment-547891687, I'll keep thinking about it.

**Comment by thomased** [comment]
Looks great — I like how it handles nonstandard wl ranges. `spectrum` is a bit vague I guess, but I'm low on ideas. Something like 'guide', 'wl_guide', 'hue_guide', 'indicator' maybe?

**Comment by Bisaloo** [comment]
`wl_guide` sounds good. I'll wait a couple of days in case we come up with something better (since this is a new feature, it's not blocking any other issue).

**Comment by Bisaloo** [comment]
Somewhat related follow up question: should other plotting functions (`peakshape()`, `aggplot()`, `plotsmooth()`, `explorespec()`) internally use `plot.rspec()`?

**Comment by thomased** [comment]
Possibly? Time/effort permitting I suppose it reduces redundancy & points of failure, but it could be a job to get it all working as before. 

Unrelated — should `wl_guide` be `wl.guide`? We jump around a bit between camelcase, snakecase, periods etc., but we seem to favour periods over underscores generally (`coldist()`, `aggplot()`, `getspec()`)?

**Comment by Bisaloo** [comment]
Ah, that's a tough one. I tend to avoid periods as multiple style guide recommend keeping dots for S3 methods (https://style.tidyverse.org/syntax.html#object-names). Here, it's not as bad since it an argument and there is no risk of confusion with a method. So maybe we should indeed favour consistency. IDK.

**Comment by thomased** [comment]
Yeah, completely agreed — I'd like snake case throughout, but we're stuck with history so perhaps we'll make the switch for consistency? More consistent, but poorer style. A tradeoff, but at least here there's minimal risk of confusion like you say.

**Pull request merged**
