### PR TITLE
Use 'geometry' instead of custom functions to compute overlap

### PR DESCRIPTION
**Pull request by Bisaloo**
``` r
devtools::install_github("davidcsterratt/geometry", subdir="pkg")
library(geometry)

ps1 <- rbox(0, C=0.5)
ps2 <- rbox(0, C=0.5) + 0.5

colnames(ps1) <- colnames(ps2) <- c("x", "y", "z")

library(microbenchmark)

microbenchmark({ pavo::voloverlap(ps1, ps2) },
               { voloverlap(ps1, ps2) })
```

It cuts execution time in half. It also removes the dependency to `rcdd`.

WIP because it should wait for `geometry` 0.4.0 to be released on CRAN. Also, at the moment `intersectn` returns an error if there is no overlap. I will try to see with the package maintainer if this could be downgraded to a warning or a message.

TODO list:

- [x] Ensure the function works when there is no overlap (either upstream change or dirty trycatch here)
- [x] Update changelog
- [x] Work with trispace
- [ ] Work with arbitrary number of dimensions / colour receptors
- [x] Completely deprecate montecarlo option (?)
- [x] Remove ref to S.Villeger code (?, it's all gone as far as I can tell)
- [x] Update vignette (?)
- [ ] Add check for required colspace args 
- [x] Remove `libgmp` dependency
- [ ] Fix plot for trispace

### CODE REVIEW

**Comment by thomased** [comment]
Cool - definitely worth keeping an eye on. Might be nice to eventually implement voloverlap more generally too — no reason it should be unique to a tcs really. Could be convenient for that.

**Comment by Bisaloo** [comment]
When this new version of `geometry` is released, we can also use [`inhulln`](https://github.com/davidcsterratt/geometry/blob/master/pkg/R/inhulln.R) to remove the `sp` dependency (it is only used once [here](https://github.com/rmaia/pavo/blob/ced4abceacb4cdc52c730f4ca83d8d21b9a6daf7/R/adjacent.R#L678)).

**Comment by thomased** [comment]
Oh great! Yeah the `sp` dependency was just temporary laziness on my part - intended to roll-my-own solution before release. But if geometry will be able to handle it that’d be perfect.

**Comment by thomased** [comment]
Just a note-to-self, that `inpoly` function (with its `sp` dependency) is also now used in `procimg` for correcting classified images. Just so I don't forget to also swap it out for `inhulln`.

**Comment by Bisaloo** [comment]
Yeah, I was looking at this yesterday. I might be a little bit harder than anticipated: `inhulln` works with convex hulls. I don't think the polygons used for image analysis are necessarily convex.

I'll look at the algorithm in `inhulln` though. If we're lucky we might still be able to use it in a roundabout way.

**Comment by Bisaloo** [comment]
Note to self: don't use `tcsvol()` at all to plot. Beyond the fact that it only works with `tcs` objects (a `if`...`else` could take care of this), it is highly inefficient in this case as it recomputes the convex hull when we already did it at the beginning of `voloverlap()`

**Comment by Bisaloo** [comment]
Okay, let's try this for a first pass. I can add the plot option for trispaces in a second time. Better than keeping this in a stale branch.

**Comment by thomased** [comment]
That's pretty awesome! I've had a poke around and haven't broken anything — looks nice. Feel free to pop it in if you're happy. Better than staying stale, like you say.

**Pull request merged**
