### PR TITLE
Max gamut

### LINKED ISSUE #66: Monochromatic loci
Calculate monochromatic loci for given vis system + illuminant.

e.g. 
```
purespec <- as.data.frame(matrix(0, 401, 401))
purespec[row(purespec) == col(purespec)] <- 1
purespec$wl <- seq(300, 700, 1)

vis.lasers <- vismodel(purespec, visual = 'apis')
lasers.tri <- colspace(vis.lasers)
plot(lasers.tri)
```

except generalised.

### PR DESCRIPTION
**Pull request by Bisaloo**
fix #66

This is something that I have been wanting to do for a long time and that I now have to do for a manuscipt in revision: I need to compute the maximum theoretical gamut given a visual system and illuminant.

This is a first pass at trying to do this but I'm not entirely sure it's the best way. I also really need to refactorize `dispace()`/`trispace()`/`tcspace()` at some point (plus address #102 and #179 while I'm at it) but I don't know if I will manage to do it in this PR. 

An example of what it produces with `triplot()`:

Rplot

### CODE REVIEW

**Comment by thomased** [comment]
Related #66 — would be awesome.

**Comment by Bisaloo** [comment]
Quality check: cie monochromatic loci

Rplot

**Comment by Bisaloo** [comment]
Currently stuck at: `vismodel()` create `-Inf` values for `qcatch = "fi"`. I need to figure out what we're supposed to do with Fechner's law when `Qi = 0`.

**Comment by thomased** [comment]
This looks awesome.

Yeah the `Qi = 0` and `Qi < 1` cases for log-transforming are longstanding. I don't have a clean answer, no-one seems to mention it which has made me think I'm missing something obvious...

**Comment by thomased** [comment]
This is super cool. Couple of quick Q's while I'm playing around:
- (1) Points should always fall inside the gamut right? Unless I'm misunderstanding how it works. e.g. centre
gamuts
- (2) It's not currently implemented for `qcatch = 'fi'` just yet correct? Because of the above `Qi = 0` issue.

**Comment by Bisaloo** [comment]
No, you're right, points should not fall outside. It's likely a bug. Could you share the code you used to produce these graphs please?

On a related note, the first graph is strange because the max gamut should always be convex and it's not the case here.

**Comment by thomased** [comment]
Lazy code:

```
data(flowers)

vis_a <- sensmodel(c(350, 450, 550))
names(vis_a) <- c('wl', 's', 'm', 'l')
mod_a <- vismodel(flowers, vis_a)
tri_a <- colspace(mod_a)

vis_b <- sensmodel(c(340, 530, 550))
names(vis_b) <- c('wl', 's', 'm', 'l')
mod_b <- vismodel(flowers, vis_b)
tri_b <- colspace(mod_b)

vis_c <- sensmodel(c(330, 340, 660))
names(vis_c) <- c('wl', 's', 'm', 'l')
mod_c <- vismodel(flowers, vis_c)
tri_c <- colspace(mod_c)

par(mfrow = c(1, 3))
plot(tri_a, gamut = TRUE)
plot(tri_b, gamut = TRUE)
plot(tri_c, gamut = TRUE)
```

**Comment by Bisaloo** [comment]
Random thought while trying to debug this: should we provide a method for `identify()` for colspace objects?

**Comment by Bisaloo** [comment]
Okay, the gamut for trispace objects is now correct. The bug was not present for dispace and tcspace objects.

On a related note, what is the best way to figure the gamut in plots?

**Comment by Bisaloo** [comment]
Issue: conversion to relative qcatches when all qcatches are zero (e.g. CIE between 300 and 390 nm) creates `NaN`.

**Comment by thomased** [comment]
This is looking awesome. Couple of quick things:

(1) Uninformative error atm when trying to use transformed qcatches
```
data(flowers)
vis.flowers <- vismodel(flowers, qcatch = 'Ei', visual = "apis", scale = 10000)
tri.flowers <- colspace(vis.flowers)
plot(tri.flowers, gamut = TRUE)
```

```
Error in convhulln(coords_mono) : 
The first argument should not contain any NAs 
```

(2) Not sure what your thoughts are, but if it'll be a while before before we solve/implement it with transformed qcatches it's probably worth mentioning that in the docs (`...currently only possible when qcatch = Qi` or something).

(3) For tetrachromats, the volume when plotted looks like it's basically ~100%. Is that right? My intuition might just be mis-calibrated, but I would've thought the effect of the minor overlaps in sensitivity should be larger. (Maybe not though, one of the benefits of tetrachromacy...).
```
vis.flowers <- vismodel(flowers, visual = 'bluetit')
tcs.flowers <- colspace(vis.flowers)
summary(tcs.flowers)
plot(tcs.flowers, gamut = TRUE)
```
tcs

**Comment by Bisaloo** [comment]
All very points:

1. Fixed by `tryCatch()` in 
2. Updated the docs of `triplot()`, `tetraplot()` and `tcsplot()` in 
3. I think the code is correct. From a theoretical point of view (and actually one reviewer said the same thing), I agree but because of their oil droplets (this is the main reason I think), most birds have very little overlap. Below are the blue tit's photoreceptor sensitivity profiles:

Rplot

The only case where it's impossible to excite only one receptor is for `m` (because there is always another receptor overlapping) and notice how it's the only place where the max gamut doesn't reach the corner in the tcs plot.

Let's try again with `sensmodel(c(350, 450, 550, 650))`, which generates a lot of overlap:

Rplot01

```r
vis.flowers <- vismodel(flowers, sensmodel(c(350, 450, 550, 650)))
tcs.flowers <- colspace(vis.flowers)
summary(tcs.flowers)
plot(tcs.flowers, gamut = TRUE)
```

Rplot02

**Comment by thomased** [comment]
Cool - all looks good to go from my perspective then. Guess my intuition was just off re: birds, but it makes sense. Benefits of a finely tuned tetrachromat!

**Pull request merged**
