### PR TITLE
Add option to plot CIE colour bg

### PR DESCRIPTION
**Pull request by Bisaloo**
Some fun with `magick`:

rplot05

~~WIP because blocked by #129~~

### CODE REVIEW

**Comment by Bisaloo** [comment]
Here my dilemma here:

- `image_read()` can read `svg` but will produce low-res or outright broken output on some platforms
- `image_read_svg()` is better but needs an additional package dependency (`rsvg`, that we could add to `Suggests`)
- it is possible to try `image_read_svg()` first and then fallback to `image_read()` if `rsvg` is not available but I don't see any way to keep meaningful error message in case of a legitimate error at the moment (e.g. wrong file path)

**Comment by thomased** [comment]
Cool — so you went for the `image_read()` in the end? Any idea roughly how often it's likely to be broken/ugly? I guess users can just flick it off it it looks weird, but ideally that'd be a minority of cases.

**Comment by Bisaloo** [comment]
Oh, right, because I squashed the commits, the history disappeared. Basically the issue mentioned in https://github.com/rmaia/pavo/pull/141#issuecomment-508525047 only apply to `svg` images. In the end, I decided to use the `png` image. After thinking about it more, there is no point using a `svg` image to rasterize it in the next line.

The `png` image will work without any problem on all platforms.

**Comment by thomased** [comment]
Awesome.

**Pull request merged**
