### PR TITLE
Alphashapes

### PR DESCRIPTION
**Pull request by Bisaloo**
- [x] `alphashape3d` in `Imports` or `Suggests`? `Imports` for now
- [ ] Add code to have a single component in vignette
- [x] Update changelog
- [x] Add overlap code
- [x] Allow different values of `avalue` for `tcsres1` and `tcsres2` in `overlap3d()`?
- [x] Discuss argument order
- [x] Discuss function names. Doesn't matter since they will be internal
- [x] Add references to paper in vignette and function doc
- [ ] Add 2D code

copy/paste from Tom on slack: 
> would it also be possible and desirable to just add an argument to the existing functions to incorporate alphashapes? Instead of independent functions. Like `vol(tcsdata, type = c('convex', 'alpha'), ...)` or whatever.

### CODE REVIEW

**Comment by Bisaloo** [comment]
I'll take care of the 2D code later. This is almost ready to merge the first version into the master branch.

My main issue right now is the order of the arguments. I changed it because it makes much more sense this way but this is a breaking change. I'm not sure this is acceptable so I can put them back at the end if necessary.

@thomased, what do you think?

**Comment by thomased** [comment]
Mmm I much prefer the arguments in that new order of yours. I guess it's breaking, but only for those people living on the edge by not explicitly specifying arguments. I know it's probably not best practice, but am fine to go with it if you're on board...

**Comment by Bisaloo** [comment]
instead of `avalue1, avalue2`, what about a single `avalue` which can be of length one or two?

**Comment by thomased** [comment]
Yeah that’s a tidy way of doing it

**Comment by Bisaloo** [comment]
I think this is ready to merge as a first step. Do you want to have another look first @thomased?

**Comment by thomased** [comment]
Oh cool, sorry for the delay. Had a poke around — looking excellent. Maybe just chuck an example in `vol()`, `voloverlap()` etc. sometime for good measure? Otherwise merge away.

Bit of a shame there are also a few `alpha` arguments relating to point transparency around the place, but nothing much to be done there.

**Pull request merged**
