### PR TITLE
Remove non-ASCII characters from ProcSpec files

### LINKED ISSUE #81: issue reading ProcSpec
@Bisaloo a user is having trouble reading in this ProcSpec file, do you think you can debug it?

code used: `test <- getspec("/Desktop/test/", ext = “ProcSpec", decimal = "," )`

File is attached, please change extension to ProcSpec (github doesn't authorize uploading it).

Thanks!

[19-c.txt](https://github.com/rmaia/pavo/files/1644459/19-c.txt)

### PR DESCRIPTION
**Pull request by Bisaloo**
fix #81

Unfortunately, I expect this has some impact on performance. On the upside, I was able to remove the `readr` dependency.

Can we use the file provided in #81 for our tests to ensure this still work correctly with faulty files in the future?

- [x] Fix issue
- [x] Add tests to prevent this issue in the future

### CODE REVIEW

**Comment by thomased** [comment]
Yeah just re: your test question - we can indeed include example specs in the `inst/testdata` directory then call them using `system.file()` from within the tests. Have a quick look at how the `getspec()` tests in `test-import.R` are structured to see what that setup looks like, if you want.

**Comment by Bisaloo** [comment]
@thomas, thank you for your answer. I was more asking from a copyright point of view. Did the user that sent you the data grant `pavo` permission to use it?

**Comment by thomased** [comment]
Ah, right, sorry. Was sent to @rmaia, but I know the guy who sent it & doubt it would be an issue. Can check. Could also perhaps just replace with random data if it's not too painful.

**Comment by Bisaloo** [comment]
I replaced the username by `user` and all values by `100.00` in the test file so it should be okay.

**Comment by thomased** [comment]
Great - cheers @Bisaloo

**Pull request merged**
