### PR TITLE
[WIP] Replace imager by magick

### PR DESCRIPTION
**Pull request by Bisaloo**
This should work. I have two questions:

- Should I completely remove everything related to `imager` (`cimg2rimg()` and `rimg2cimg()` as well as `imager` from `DESCRIPTION`)?

- Should I move back `magick` to the `Imports` section of the `DESCRIPTION`?

### CODE REVIEW

**Comment by Bisaloo** [comment]
Some figures to illustrate the impact of this change:

dep_imager
magick_deps

**Comment by thomased** [comment]
Hah — that dependency map is nuts.

(1) I think I'd leave the imager functions, and keep imager in suggests. None of it does any harm, and just gives users some more options, since imager and magick are the two main image-processing packages at the moment. I'll update the paper & vignette to mention it.

(2) Yeah maybe try imports? Happy to follow your lead, but it's so lightweight that it might just be worth importing. Plus there may be reason to weave in some more functionality via `procimg` in the future.

**Comment by Bisaloo** [comment]
Btw, `rimg2magick` and `magick2rimg` are vectorized and work out of the box with lists of images. I'm not sure if that's possible for `rimg2cimg` and `cimg2rimg` but it would probably nice as well.

**Comment by Bisaloo** [comment]
Okay, there is a last border effect. `magick2rimg` converts `magick` object to a `c("rimg", "list")` object, even when there is only one element.

This may actually be what we want because that's probably what caused the issue which required to duplicate a lot of the code with `if (multi) {} else {}`. Now everything is a list (with sometimes just one element).

The main issue is that until the rest of the code is updated, we would have both formats for single element `rimg` (list and array), which is a bit clunky.

What do you think? I may be missing something.

**Comment by thomased** [comment]
Interesting idea about using lists. If all images were in a list, I guess we could trim most of that control code. 

It might trip users up with single images I suppose, because it's a bit unintuitive for a single object to be part of a list (for indexing etc.)? And if they bring/load their own images outside of pavo we need to be able to handle that. I guess we could always coerce to `rimg` and return a list, but again it might be a little weird to give an array to `procimg` for some simple processing and get a one-element list in return. Could be worth it of course — the code would definitely be tidier. Just thinking out loud.

**Comment by Bisaloo** [comment]
I think it's possible to keep this invisible to users. All they would see is that we return `rimg` objects. In most cases, they should not be care about which class `rimg` objects are inheriting. 

One case where it could indeed be slightly annoying if is they keep going back and forth between `pavo` and their own code where they consider imgs as arrays. But I think that will always be an issue working with custom classes, no matter what we do.

Right now, I find it a bit more confusing that two `rimg` objects do not necessarily have a same class inheritance. Some are `c("rimg", "array")` and some are `c("rimg", "list")`. And as you've seen, it requires you to duplicate the code to work around this. At the moment, a simple `lapply` won't work in the same fashion in both cases. Similarly, you talk about indexing but right now `img[[1]]` does not behave in the same way whether you have a single img or multiple imgs. It worked for you because you designed the code so you knew why it didn't work and how to work around it but I don't think it's something one would really expect.

**Comment by thomased** [comment]
Yeah I'm sure you're right about it making sense for me because I wrote it! The `c('rimg', 'list')` case was an ugly hack really, just so that `plot.rimg()` would work with lists of `rimg`'s. 

An image, at it's most basic (for me), is a 3d array, so that's the 'atom' in my mind, or the _true_ `rimg`. Then if you want a bunch of them together, store them in a list, like you would if you had a list of similar data.frames or whatever (speaking as a hypothetical user). But I understand the two forms of `rimg` aren't ideal, for the reasons you mention.

There are some practical issues too that make me prefer `c('rimg', 'array')` as the basic unit. Namely, `plot.rimg()`, `summary.rimg()` etc. all need to work with _elements_ of a list of images, so they always need to be `rimg` themselves as far as I can see. The user should be able to only plot the second image using `plot(images[[2]])`, `summary(images[[2]])`, for example. Plus every element in the list (every individual image) needs a bunch of custom attributes like scales, focal object coordinates, names, that will vary from image to image. Just having `c('rimg', 'list')` wouldn't allow for any of that (I'm pretty sure, it's late).

If there were a way to have `plot.rimg()` recognise lists of `rimg`'s _without itself having to be_ `rimg` that'd be my preferred solution at this stage. The only way I currently know of making that work would would be to make lists their own separate class again (`rimglist`, or something), then have simple wrapper functions (`plot.rimglist()`) that basically just pass through to `plot.rimg()`. That'd also basically be invisible to the user, but would as least make inheritance less ambiguous because `rimg` would only ever be `c('rimg', 'array')`. (?)

**Comment by Bisaloo** [comment]
Okay, this is going to be my last comment on this and then I'm leaving the final decision to you :wink:.

> An image, at it's most basic (for me), is a 3d array, so that's the 'atom' in my mind, or the true rimg. Then if you want a bunch of them together, store them in a list, like you would if you had a list of similar data.frames or whatever (speaking as a hypothetical user).

I agree it's probably what makes more sense conceptually but I am not sure this implies that it's the best choice in terms of usability as well as code maintainability.

> Namely, `plot.rimg()`, `summary.rimg()` etc. all need to work with elements of a list of images, so they always need to be `rimg` themselves as far as I can see. The user should be able to only plot the second image using `plot(images[[2]])`, `summary(images[[2]])`, for example.

This does not prevent us from implementing I am proposing IMO. Actually, it's *exactly* what `magick` does.

``` r
library(magick)
#> Linking to ImageMagick 6.8.9.9
#> Enabled features: cairo, fontconfig, freetype, fftw, lcms, pango, rsvg, x11
#> Disabled features: ghostscript, webp

heliconius <- image_read(system.file("testdata/images/h_melpomene.jpg", package = "pavo"))
papilio <- image_read(system.file("testdata/images/papilio.png", package = "pavo"))

class(heliconius)
#> [1] "magick-image"
class(papilio)
#> [1] "magick-image"

both <- c(heliconius, papilio)

class(both)
#> [1] "magick-image"

class(both[1])
#> [1] "magick-image"

plot(heliconius)

plot(both[1])
```



``` r
plot(both[2])
```



```r
summary(both)
#      Length        Class         Mode 
#           2 magick-image  externalptr 

summary(both[1])
#      Length        Class         Mode 
#           1 magick-image  externalptr 
```

This is also why I suggested relying more on `magick`, because as far as I can tell, it already does a lot exactly the way we want things to be.

To be honest, I'm not familiar enough with R class system to know exactly how it is working but at the very least, it's proving that it is possible.

As I said, the final choice is yours. Feel free to take some time to think about it and possibly play a bit with `magick` and let me know how you would like me to edit this PR.

**PS:** I'm only seeing your edit now that I've written this message. I'm still posting it because it shows how much cool stuff `magick` can do. I understand you have other things to do, this can wait, no worries.

**Comment by Bisaloo** [comment]
On another note, I was thinking yesterday that it would be useful if `as.rimg` could automatically use `cimg2rimg` and `magick2rimg` whenever necessary. In other words, we would specific `as.rimg` methods for `cimg` and `magick` classes. I think I know how to do it, I will have a look soon.

**Comment by Bisaloo** [comment]
Or we could even completely remove `cimg2rimg` and `magick2rimg` and users would use `as.rimg` in all cases. I'm not sure what's best.

**Comment by thomased** [comment]
Ah, very cool. No, obviously I don’t understand it as well as I thought, so will do some reading/experimenting before causing more confusion :)

**Comment by thomased** [comment]
In general though I'm all for the move toward magick — just need to understand it a bit better.

And your `as.rimg` idea sounds great. I'd be inclined to get rid of `cimg2rimg` and `magick2rimg`, or at least stop exporting them & use them internally (if useful). So users would only need `as.rimg` to convert an array, cimg, or magick to rimg. Love it. 

Shouldn't be too tricky — I can take a look as well.

**Comment by thomased** [comment]
No, my fault. I just let this sit here as a todo. Slightly longer term, I'm keen to go more all-in with magick — you've sold me. I just need to get the class thing straight before diving in, as there'll be a fair bit of reshuffling to be done overall.

Shorter-term, your `as.rimg` change is awesome, along with the addition of `rimg2magick` and moving `magick` to Imports. If it's not a pain to split those smaller changes off and pop them in now feel free to? It might be convenient to have them roughed in while figuring out the internal class stuff actually. Otherwise it can wait for the larger reworking though, no pressure at all.

So it's just waiting for me really :grimacing:

**Comment by Bisaloo** [comment]
No worries! I can indeed make the current changes work without diving too deep in the class stuff. I can open a new WIP PR with the remaining changes I couldn't add here.

I'll try to do this soon.

**Comment by thomased** [comment]
I think this is all done on the `2magick` branch now. I had to some other stuff at the same time and just find it easier working on main branch rather than via PR sorry. Feel free to tinker with it, try stuff out of course.

**Pull request closed without merging**
